Spring:
  web:
    resources:
      static-locations: classpath:/templates
#上传文件使用
servlet:
  multipart:
    #单个文件最大上传大小
    max-file-size: 50MB
    #每次请求上传文件大小最大值
    max-request-size: 100MB

#自定义参数
define:
  nginx:
    #windows path
    path: D:\upload\